# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrokeLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_length', models.PositiveSmallIntegerField(default=25)),
                ('glide_distance', models.PositiveSmallIntegerField()),
                ('stroke_count', models.PositiveSmallIntegerField()),
                ('wingspan', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
