# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strokelength',
            name='today',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='strokelength',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strokelength',
            name='glide_distance',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='strokelength',
            name='stroke_count',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='strokelength',
            name='wingspan',
            field=models.PositiveSmallIntegerField(default=68),
        ),
    ]
