# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl', '0002_auto_20170128_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strokelength',
            name='today',
            field=models.DateField(),
        ),
    ]
